# Generated by Django 6.0.2 on 2026-02-10 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='tank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='monitoring.tank'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='capacity',
            field=models.FloatField(blank=True, default=0.0, help_text='Liters', null=True),
        ),
        migrations.AlterField(
            model_name='tank',
            name='fish_species',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tank',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to=settings.AUTH_USER_MODEL),
        ),
    ]
