# Generated by Django 6.0.2 on 2026-02-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_eventlog_tank_alter_tank_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorreading',
            old_name='recorded_at',
            new_name='created_at',
        ),
    ]
