# Generated by Django 6.0.2 on 2026-02-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_rename_recorded_at_sensorreading_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='target_ph',
            field=models.FloatField(default=7.0, help_text='권장 pH'),
        ),
        migrations.AddField(
            model_name='tank',
            name='target_temp',
            field=models.FloatField(default=25.0, help_text='권장 온도'),
        ),
    ]
