# Generated by Django 6.0.2 on 2026-02-11 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_tank_target_ph_tank_target_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LIGHT', '조명'), ('FILTER', '여과기'), ('HEATER', '히터')], max_length=20)),
                ('is_on', models.BooleanField(default=False)),
                ('last_action_at', models.DateTimeField(auto_now=True)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='monitoring.tank')),
            ],
        ),
    ]
