# Generated by Django 5.2.5 on 2026-02-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_devicecontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='last_water_change',
            field=models.DateField(blank=True, help_text='마지막 환수 날짜', null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='water_change_period',
            field=models.IntegerField(default=7, help_text='환수 주기(일)'),
        ),
    ]
