# Generated by Django 6.0.2 on 2026-03-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_tank_last_water_change_tank_water_change_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='turbidity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='water_quality_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='tank',
            name='filter_is_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tank',
            name='filter_mode',
            field=models.CharField(choices=[('MANUAL', '수동'), ('AUTO', '자동')], default='MANUAL', max_length=10),
        ),
    ]
