# Generated by Django 6.0.2 on 2026-04-14 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_sensorreading_turbidity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sensorreading',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tank',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='devicecontrol',
            name='is_auto',
            field=models.BooleanField(default=True, help_text='True: 자동 제어 / False: 수동 제어'),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='dissolved_oxygen',
            field=models.FloatField(default=0.0, help_text='용존산소량(mg/L)'),
        ),
        migrations.AlterField(
            model_name='devicecontrol',
            name='type',
            field=models.CharField(choices=[('HEATER', '히터'), ('COOLING', '냉각팬'), ('FILTER', '여과기'), ('AIR_PUMP', '에어펌프'), ('FEEDER', '급이기'), ('LIGHT', '조명')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='ph',
            field=models.FloatField(help_text='pH'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='temperature',
            field=models.FloatField(help_text='수온(°C)'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='turbidity',
            field=models.FloatField(default=0.0, help_text='탁도(NTU)'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='water_level',
            field=models.FloatField(default=100.0, help_text='수위(%)'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='water_quality_score',
            field=models.IntegerField(default=100, help_text='수질 종합 점수(0~100)'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='capacity',
            field=models.FloatField(blank=True, default=0.0, help_text='용량(L)', null=True),
        ),
        migrations.AlterField(
            model_name='tank',
            name='last_water_change',
            field=models.DateField(blank=True, help_text='마지막 환수일', null=True),
        ),
        migrations.AlterField(
            model_name='tank',
            name='target_temp',
            field=models.FloatField(default=25.0, help_text='권장 수온(°C)'),
        ),
        migrations.AlterUniqueTogether(
            name='devicecontrol',
            unique_together={('tank', 'type')},
        ),
        migrations.CreateModel(
            name='FishBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_count', models.IntegerField(default=0, help_text='탐지된 개체 수')),
                ('overlap_frames', models.IntegerField(default=0, help_text='겹침 발생 프레임 수')),
                ('activity_level', models.FloatField(default=0.0, help_text='활동량(px/frame 이동평균)')),
                ('dominant_zone', models.CharField(choices=[('TOP', '상층'), ('MID', '중층'), ('BOT', '하층')], default='MID', help_text='주 체류 구역', max_length=3)),
                ('zone_top_ratio', models.FloatField(default=0.0, help_text='상층 체류 비율(0~1)')),
                ('zone_mid_ratio', models.FloatField(default=0.0, help_text='중층 체류 비율(0~1)')),
                ('zone_bot_ratio', models.FloatField(default=0.0, help_text='하층 체류 비율(0~1)')),
                ('size_index', models.FloatField(default=0.0, help_text='상대 크기 지표(%)')),
                ('feeding_score', models.IntegerField(default=0, help_text='급이 반응 점수(0~100)')),
                ('status', models.CharField(choices=[('EXCELLENT', '매우 좋음'), ('GOOD', '좋음'), ('NORMAL', '보통'), ('WARNING', '주의'), ('POOR', '나쁨')], default='NORMAL', max_length=10)),
                ('is_anomaly', models.BooleanField(default=False, help_text='이상 행동 감지 여부')),
                ('note', models.TextField(blank=True, help_text='AI 권장사항 또는 이상 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='monitoring.tank')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
