# Generated by Django 6.0.2 on 2026-04-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_add_feeding_growth_activity_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypattern',
            name='anomaly_hours',
            field=models.JSONField(default=list, help_text='이상 활동 감지 시간대 목록'),
        ),
        migrations.AlterField(
            model_name='activitypattern',
            name='baseline_std',
            field=models.FloatField(default=0.0, help_text='Baseline 속도 표준편차(px/s)'),
        ),
        migrations.AlterField(
            model_name='activitypattern',
            name='daytime_activity',
            field=models.FloatField(default=0.0, help_text='주간(6~22시) 평균 활동량'),
        ),
        migrations.AlterField(
            model_name='activitypattern',
            name='hourly_activity',
            field=models.JSONField(default=dict, help_text='시간대별 평균 활동량 {hour: avg_speed}'),
        ),
        migrations.AlterField(
            model_name='activitypattern',
            name='nighttime_activity',
            field=models.FloatField(default=0.0, help_text='야간(22~6시) 평균 활동량'),
        ),
        migrations.AlterField(
            model_name='feedingresponse',
            name='ar_ratio',
            field=models.FloatField(default=0.0, help_text='활동증가율: 급이중/급이전 avg_speed 비율'),
        ),
        migrations.AlterField(
            model_name='feedingresponse',
            name='rt_seconds',
            field=models.FloatField(default=0.0, help_text='반응시간(초): 급이→수면 첫 접근까지'),
        ),
        migrations.AlterField(
            model_name='feedingresponse',
            name='sf_ratio',
            field=models.FloatField(default=0.0, help_text='수면접근빈도: 급이구간 TOP zone 체류 비율'),
        ),
        migrations.AlterField(
            model_name='fishbehavior',
            name='activity_level',
            field=models.FloatField(default=0.0, help_text='활동량(px/s 이동평균)'),
        ),
        migrations.AlterField(
            model_name='growthrecord',
            name='estimated_weight',
            field=models.FloatField(default=0.0, help_text='추정 체중(g) — W=0.01049×TL^3.14'),
        ),
        migrations.AlterField(
            model_name='growthrecord',
            name='size_index',
            field=models.FloatField(help_text='size_index(%) = bbox면적/프레임면적×100'),
        ),
    ]
