# Generated by Django 6.0.2 on 2026-05-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_alter_activitypattern_anomaly_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tank',
            name='filter_is_on',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='filter_mode',
        ),
        migrations.AddField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(choices=[('SENSOR_ALERT', '수질 경보'), ('DEVICE_CHANGE', '장치 상태 변경'), ('ANOMALY', '행동 이상 감지'), ('FEEDING', '급이 이벤트'), ('OVERFEEDING', '과급여 감지'), ('WATER_CHANGE', '환수 알림'), ('SYSTEM', '시스템')], default='SYSTEM', help_text='이벤트 종류', max_length=20),
        ),
    ]
