# Generated by Django 6.0.2 on 2026-05-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_remove_tank_filter_is_on_remove_tank_filter_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='pi_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Raspberry Pi IP', null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='pi_last_seen',
            field=models.DateTimeField(blank=True, help_text='Pi 마지막 접속 시각', null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='pi_stream_port',
            field=models.IntegerField(default=8080, help_text='카메라 스트림 포트'),
        ),
    ]
