# Generated by Django 6.0.2 on 2026-05-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_tank_pi_ip_tank_pi_last_seen_tank_pi_stream_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='airpump_off_do',
            field=models.FloatField(default=6.0, help_text='에어펌프 OFF 기준(mg/L)'),
        ),
        migrations.AddField(
            model_name='tank',
            name='airpump_on_do',
            field=models.FloatField(default=4.0, help_text='에어펌프 ON 기준(mg/L)'),
        ),
        migrations.AddField(
            model_name='tank',
            name='cooling_off_temp',
            field=models.FloatField(default=23.0, help_text='냉각팬 OFF 기준(°C)'),
        ),
        migrations.AddField(
            model_name='tank',
            name='cooling_on_temp',
            field=models.FloatField(default=24.0, help_text='냉각팬 ON 기준(°C)'),
        ),
        migrations.AddField(
            model_name='tank',
            name='do_min',
            field=models.FloatField(default=5.0, help_text='DO 최솟값(mg/L)'),
        ),
        migrations.AddField(
            model_name='tank',
            name='feeding_amount_g',
            field=models.FloatField(default=0.1, help_text='1회 급이량(g)'),
        ),
        migrations.AddField(
            model_name='tank',
            name='feeding_auto',
            field=models.BooleanField(default=True, help_text='자동 급이 사용'),
        ),
        migrations.AddField(
            model_name='tank',
            name='feeding_times',
            field=models.CharField(default='08:00,12:00,18:00', help_text='급이 시간 (콤마 구분)', max_length=200),
        ),
        migrations.AddField(
            model_name='tank',
            name='filter_off_ntu',
            field=models.FloatField(default=20.0, help_text='여과기 OFF 기준(NTU)'),
        ),
        migrations.AddField(
            model_name='tank',
            name='filter_on_ntu',
            field=models.FloatField(default=50.0, help_text='여과기 ON 기준(NTU)'),
        ),
        migrations.AddField(
            model_name='tank',
            name='heater_off_temp',
            field=models.FloatField(default=22.0, help_text='히터 OFF 기준(°C)'),
        ),
        migrations.AddField(
            model_name='tank',
            name='heater_on_temp',
            field=models.FloatField(default=21.0, help_text='히터 ON 기준(°C)'),
        ),
        migrations.AddField(
            model_name='tank',
            name='light_auto',
            field=models.BooleanField(default=True, help_text='조명 자동 제어'),
        ),
        migrations.AddField(
            model_name='tank',
            name='light_off_hour',
            field=models.IntegerField(default=20, help_text='조명 소등 시각(시)'),
        ),
        migrations.AddField(
            model_name='tank',
            name='light_on_hour',
            field=models.IntegerField(default=8, help_text='조명 점등 시각(시)'),
        ),
        migrations.AddField(
            model_name='tank',
            name='ph_max',
            field=models.FloatField(default=8.0, help_text='pH 최댓값'),
        ),
        migrations.AddField(
            model_name='tank',
            name='ph_min',
            field=models.FloatField(default=6.5, help_text='pH 최솟값'),
        ),
        migrations.AddField(
            model_name='tank',
            name='temp_max',
            field=models.FloatField(default=24.0, help_text='수온 최댓값(°C)'),
        ),
        migrations.AddField(
            model_name='tank',
            name='temp_min',
            field=models.FloatField(default=21.0, help_text='수온 최솟값(°C)'),
        ),
        migrations.AddField(
            model_name='tank',
            name='turbidity_max',
            field=models.FloatField(default=50.0, help_text='탁도 최댓값(NTU)'),
        ),
    ]
