# Generated by Django 5.1 on 2026-08-15 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_alter_tank_pi_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('category', models.CharField(choices=[('TEMP', '수온'), ('PH', 'pH'), ('DO', '용존산소'), ('TURBIDITY', '탁도'), ('BEHAVIOR', '행동'), ('SYSTEM', '시스템')], max_length=20)),
                ('level', models.CharField(choices=[('INFO', '정보'), ('WARNING', '주의'), ('DANGER', '위험')], default='WARNING', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('causes', models.JSONField(blank=True, default=list, help_text='발생 가능한 원인 목록')),
                ('effects', models.JSONField(blank=True, default=list, help_text='물고기에게 미칠 수 있는 영향 목록')),
                ('actions', models.JSONField(blank=True, default=list, help_text='사용자 조치 방법 목록')),
                ('prevention', models.JSONField(blank=True, default=list, help_text='예방 방법 목록')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TankStateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.FloatField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('state_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='monitoring.statecode')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_events', to='monitoring.tank')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['tank', 'is_resolved'], name='monitoring__tank_id_da6852_idx'), models.Index(fields=['tank', 'state_code', 'is_resolved'], name='monitoring__tank_id_c81d6f_idx')],
            },
        ),
    ]
