# Generated by Django 5.1 on 2026-08-25 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0016_seed_state_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishActivityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_id', models.IntegerField(help_text='ByteTrack 개체 ID')),
                ('activity_level', models.FloatField(default=0.0, help_text='개체 활동량(px/s)')),
                ('dominant_zone', models.CharField(choices=[('TOP', '상층'), ('MID', '중층'), ('BOT', '하층')], default='MID', max_length=3)),
                ('abr_score', models.FloatField(default=0.0, help_text='개체 이상행동율(0~1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('behavior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish_details', to='monitoring.fishbehavior')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish_activity_details', to='monitoring.tank')),
            ],
            options={
                'ordering': ['fish_id'],
            },
        ),
    ]
