# Generated by Django 6.0.2 on 2026-02-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('DAILY', '일간 리포트'), ('WEEKLY', '주간 리포트'), ('MONTHLY', '월간 리포트'), ('STAT', '통계 리포트')], max_length=10),
        ),
    ]
