# Generated by Django 6.0.2 on 2026-03-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_options_alter_report_report_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'AI 리포트', 'verbose_name_plural': 'AI 리포트 목록'},
        ),
        migrations.AddField(
            model_name='report',
            name='avg_ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='avg_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='water_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.TextField(help_text='AI가 생성한 리포트 상세 내용'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('DAILY', '일간 리포트'), ('WEEKLY', '주간 리포트'), ('MONTHLY', '월간 리포트')], default='DAILY', max_length=10),
        ),
    ]
